### ISSUE TITLE
Menu & map do not fill screen height

### ISSUE THREAD

**Issue by mikeyavorsky** [codeforboston/migrant_service_map#23]
Menu bar and map do not fill screen space. https://www.dropbox.com/s/9ddzzf6py6aun6r/Screenshot%202018-12-11%2012.57.49.png?dl=0
Reproduced in Safari and Google Chrome.

Does the mapbox stylesheet override values for map-container or map?
`style: 'mapbox://styles/refugeeswelcome/cjh9k11zz15ds2spbs4ld6y9o', // stylesheet location` in src/map.js

**Comment by mikeyavorsky** [comment]
On initial load, map occupies ~300px within 758px canvass with a screen height >= ~900px. On resizing the window, map expands to fill ~700px canvass.

**Comment by sashamaryl** [comment]
issue no longer present after latest merges
